version: "3.7"
services:
  database:
    container_name: elearning-clone-postgres_container
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  server:
    container_name: elearning-clone-container
    build:
      context: .
      dockerfile: Dockerfile
    # restart: on-failure
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - 4000:4000
volumes:
  pgdata: