version: "3.7"
services:
  database:
    container_name: elearning-clone-postgres_container_dev
    image: postgres:latest
    restart: always
    env_file:
      - ../.env
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  server:
    container_name: elearning-clone-container_dev
    build:
      context: ../
      dockerfile: dev-setup/Dockerfile
    # restart: on-failure
    volumes:
      - ../:/usr/src/app/
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    env_file: ../.env
    depends_on:
      - database
    networks:
      - default
    ports:
      - '0.0.0.0:4000:4000'
volumes:
  pgdata: