version: "3.7"
services:
  database:
    container_name: elearning-clone-postgres_container_dev
    image: postgres:latest
    restart: always
    env_file:
      - ../.env
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  server:
    container_name: elearing-clone-container_dev
    build:
      context: ../
      dockerfile: dev-setup/Dockerfile
    # restart: on-failure
    volumes:
      - ..:/src/
    env_file: ../.env
    depends_on:
      - database
    networks:
      - default
    ports:
      - 4000:4000
  pgadmin:
    image: dpage/pgadmin4
    container_name: elearning-clone-pgadmin_container_dev
    env_file: ../.env
    depends_on:
      - database
    ports:
      - "5051:80"
    restart: unless-stopped
volumes:
  pgdata: