name: deploy-prod

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: docker-practice/actions-setup-docker@master
      - run: |
          docker version
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build docker image
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          docker build . -t ${{ secrets.APP_DOCKER_NAME }}:$git_hash
          docker images
          docker image tag ${{ secrets.APP_DOCKER_NAME }}:$git_hash ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.APP_DOCKER_NAME }}:$git_hash
          docker image push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.APP_DOCKER_NAME }}:$git_hash
